openapi: 3.0.0
info:
  title: Astro Web - Display Sources Data API
  description: Homepage API displaying first 10 rows from Sources table in SIMPLE.sqlite database
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /:
    get:
      summary: Homepage - Display Sources Table
      description: Displays the main homepage with the first 10 rows from the Sources table. On database error, displays error message instead.
      tags:
        - Web Pages
      responses:
        '200':
          description: Successfully rendered homepage with Sources table
          content:
            text/html:
              schema:
                type: string
                description: HTML page containing Sources table with columns (source, ra, dec, epoch, equinox, shortname, reference, other_references, comments)
                example: "<html><body><table><tr><th>source</th>...</tr></table></html>"
          headers:
            X-Sources-Count:
              description: Number of Sources rows displayed (0-10)
              schema:
                type: integer
                example: 10
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    SourcesRow:
      type: object
      description: A single row from the Sources table
      properties:
        source:
          type: string
          description: Unique source identifier
          example: "2MASS J12345678-0123456"
          nullable: true
        ra:
          type: number
          format: float
          description: Right ascension in degrees
          example: 123.456789
          nullable: true
        dec:
          type: number
          format: float
          description: Declination in degrees
          example: -12.345678
          nullable: true
        epoch:
          type: number
          format: float
          description: Epoch of coordinates
          example: 2000.0
          nullable: true
        equinox:
          type: string
          description: Equinox reference
          example: "J2000.0"
          nullable: true
        shortname:
          type: string
          description: Short catalog name
          example: "J1234-0123"
          nullable: true
        reference:
          type: string
          description: Primary reference
          example: "2019ApJ...123..456A"
          nullable: true
        other_references:
          type: string
          description: Additional references
          example: "2010MNRAS..987..321B, 2020AJ....456..789C"
          nullable: true
        comments:
          type: string
          description: Additional notes
          example: "High proper motion source"
          nullable: true
    Error:
      type: object
      properties:
        detail:
          type: string
          description: Error message
      example:
        detail: "Sources data could not be loaded at this time."
tags:
  - name: Web Pages
    description: HTML page endpoints
  - name: Database
    description: Sources table data display

