openapi: 3.0.0
info:
  title: Astro Web - Hello World API
  description: Simple web API for Hello World website demonstrating FastAPI + Jinja2 + Bokeh stack
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /:
    get:
      summary: Homepage - Hello World
      description: Displays the main homepage with "Hello World" content and an interactive scatter plot visualization
      tags:
        - Web Pages
      responses:
        '200':
          description: Successfully rendered homepage
          content:
            text/html:
              schema:
                type: string
                example: "<html>...</html>"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /{path:path}:
    get:
      summary: 404 Not Found
      description: Catch-all route for non-existent pages
      parameters:
        - name: path
          in: path
          required: true
          schema:
            type: string
          description: The requested path that was not found
      responses:
        '404':
          description: Page not found
          content:
            text/html:
              schema:
                type: string
                example: "<html>Page not found</html>"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        detail:
          type: string
          description: Error message
tags:
  - name: Web Pages
    description: HTML page endpoints

