openapi: 3.0.0
info:
  title: Astro Web - Individual Source Inventory API
  description: Endpoint for displaying comprehensive inventory data for a single astronomical source
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /source/{source_name}:
    get:
      summary: Individual Source Inventory Page
      description: Displays all data associated with a specific source across multiple related tables (Sources, Photometry, Spectra, Parallaxes, ProperMotions, etc.). Each data type is displayed as a separate table. Only tables with data are shown. URL-encoded source names are automatically decoded by FastAPI.
      tags:
        - Web Pages
      parameters:
        - name: source_name
          in: path
          required: true
          description: URL-encoded source identifier (e.g., "2MASS J12345678+0123456" becomes "2MASS%20J12345678%2B0123456")
          schema:
            type: string
          example: "2MASS J12345678+0123456"
      responses:
        '200':
          description: Successfully rendered inventory page with source data
          content:
            text/html:
              schema:
                type: string
                description: HTML page with navigation bar and multiple data tables (Sources, Photometry, Spectra, etc.)
          headers:
            X-Inventory-Tables:
              description: Number of data tables displayed on page
              schema:
                type: integer
                example: 5
        '404':
          description: Source not found
          content:
            text/html:
              schema:
                type: string
                description: Error page indicating source was not found
        '500':
          description: Server error or database unavailable
          content:
            text/html:
              schema:
                type: string
                description: Error page indicating database temporarily unavailable
components:
  schemas:
    SourceInventoryData:
      type: object
      description: Complete inventory data for a source, returned as dictionary of table names to data records
      properties:
        Sources:
          type: array
          items:
            type: object
            description: Source record with coordinates, reference, etc.
            properties:
              source:
                type: string
                example: "2MASS J12345678+0123456"
              ra:
                type: number
                format: double
                example: 188.741250
              dec:
                type: number
                format: double
                example: 0.545833
              reference:
                type: string
                example: "Smith2020"
        Photometry:
          type: array
          items:
            type: object
            description: Photometry measurement record
            properties:
              source:
                type: string
              band:
                type: string
                example: "2MASS.H"
              magnitude:
                type: number
                format: double
              magnitude_error:
                type: number
                format: double
              reference:
                type: string
        Spectra:
          type: array
          items:
            type: object
            description: Spectrum record
            properties:
              source:
                type: string
              regime:
                type: string
              observation_date:
                type: string
                format: date
              telescope:
                type: string
              instrument:
                type: string
              reference:
                type: string
              access_url:
                type: string
    Error:
      type: object
      properties:
        detail:
          type: string
          description: Error message
      examples:
        SourceNotFound:
          value:
            detail: "Source '2MASS J12345678+0123456' not found"
        DatabaseError:
          value:
            detail: "Database temporarily unavailable"
tags:
  - name: Web Pages
    description: HTML page endpoints with source inventory display
  - name: Inventory
    description: Individual source data retrieval and display

