openapi: 3.0.3
info:
  title: Astro-Web Search API
  description: API endpoints for astronomical object search functionality
  version: 1.0.0
  contact:
    name: Astro-Web Development Team

servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /search:
    get:
      summary: Display search form page
      description: Renders the search form page with input field and submit button
      tags:
        - Search
      responses:
        '200':
          description: Search form page rendered successfully
          content:
            text/html:
              schema:
                type: string
              example: |
                <!DOCTYPE html>
                <html>
                <head><title>Search Astronomical Objects</title></head>
                <body>
                  <h1>Search Astronomical Objects</h1>
                  <form method="post" action="/search/results">
                    <input type="text" name="query" placeholder="Enter search term..." required>
                    <button type="submit">Search</button>
                  </form>
                </body>
                </html>

  /search/results:
    post:
      summary: Execute search and display results
      description: Processes search query and displays results in DataTable format
      tags:
        - Search
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: Search term for astronomical objects
                  example: "NGC 1234"
                  minLength: 1
                  maxLength: 1000
      responses:
        '200':
          description: Search results displayed successfully
          content:
            text/html:
              schema:
                type: string
              example: |
                <!DOCTYPE html>
                <html>
                <head>
                  <title>Search Results</title>
                  <link rel="stylesheet" href="/static/dataTables.css">
                </head>
                <body>
                  <h1>Search Results for "NGC 1234"</h1>
                  <table id="resultsTable">
                    <thead>
                      <tr>
                        <th>Source</th>
                        <th>RA</th>
                        <th>Dec</th>
                        <th>Epoch</th>
                        <th>Equinox</th>
                        <th>Shortname</th>
                        <th>Reference</th>
                        <th>Other References</th>
                        <th>Comments</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td><a href="/inventory/NGC1234">NGC 1234</a></td>
                        <td>123.45</td>
                        <td>67.89</td>
                        <td>2015.5</td>
                        <td>J2000</td>
                        <td>NGC1234</td>
                        <td>Smith 2020</td>
                        <td>Jones 2019, Brown 2021</td>
                        <td>Bright galaxy</td>
                      </tr>
                    </tbody>
                  </table>
                  <script src="/static/dataTables.js"></script>
                  <script>
                    $('#resultsTable').DataTable();
                  </script>
                </body>
                </html>
        '400':
          description: Invalid search request
          content:
            text/html:
              schema:
                type: string
              example: |
                <!DOCTYPE html>
                <html>
                <head><title>Search Error</title></head>
                <body>
                  <h1>Search Error</h1>
                  <p>Please enter a search term</p>
                  <a href="/search">Back to Search</a>
                </body>
                </html>
        '500':
          description: Server error during search
          content:
            text/html:
              schema:
                type: string
              example: |
                <!DOCTYPE html>
                <html>
                <head><title>Search Error</title></head>
                <body>
                  <h1>Search Error</h1>
                  <p>An error occurred during search</p>
                  <a href="/search">Back to Search</a>
                </body>
                </html>

  /api/search:
    post:
      summary: Search astronomical objects (API endpoint)
      description: Programmatic API endpoint for searching astronomical objects
      tags:
        - Search API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: Search term for astronomical objects
                  example: "NGC 1234"
                  minLength: 1
                  maxLength: 1000
                session_id:
                  type: string
                  description: Optional session identifier
                  example: "session_12345"
      responses:
        '200':
          description: Search completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        source:
                          type: string
                          example: "NGC 1234"
                        ra:
                          type: number
                          format: float
                          example: 123.45
                        dec:
                          type: number
                          format: float
                          example: 67.89
                        epoch:
                          type: number
                          format: float
                          example: 2015.5
                        equinox:
                          type: string
                          example: "J2000"
                        shortname:
                          type: string
                          example: "NGC1234"
                        reference:
                          type: string
                          example: "Smith 2020"
                        other_references:
                          type: string
                          example: "Jones 2019, Brown 2021"
                        comments:
                          type: string
                          example: "Bright galaxy"
                  total_count:
                    type: integer
                    example: 1
                  query_text:
                    type: string
                    example: "NGC 1234"
                  search_time:
                    type: string
                    format: date-time
                    example: "2025-01-27T10:30:00Z"
                  execution_time:
                    type: number
                    format: float
                    example: 0.123
        '400':
          description: Invalid search request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "validation_error"
                  message:
                    type: string
                    example: "Query parameter is required"
                  query_text:
                    type: string
                    example: ""
        '500':
          description: Server error during search
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "search_error"
                  message:
                    type: string
                    example: "An error occurred during search"
                  query_text:
                    type: string
                    example: "NGC 1234"

components:
  schemas:
    SearchQuery:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: Search term for astronomical objects
          minLength: 1
          maxLength: 1000
        session_id:
          type: string
          description: Optional session identifier

    AstronomicalObject:
      type: object
      properties:
        source:
          type: string
          description: Primary identifier/name of the astronomical object (hyperlinked column)
        ra:
          type: number
          format: float
          description: Right Ascension coordinate in degrees
          minimum: 0
          maximum: 360
        dec:
          type: number
          format: float
          description: Declination coordinate in degrees
          minimum: -90
          maximum: 90
        epoch:
          type: number
          format: float
          description: Decimal year for coordinates (e.g., 2015.5)
        equinox:
          type: string
          description: Equinox reference frame year (e.g., J2000)
        shortname:
          type: string
          description: Short name for the source (marked for deletion in schema)
        reference:
          type: string
          description: Discovery reference for the source
        other_references:
          type: string
          description: Additional references, comma-separated
        comments:
          type: string
          description: Free form comments about the object

    SearchResults:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/AstronomicalObject'
        total_count:
          type: integer
          description: Total number of matching objects found
        query_text:
          type: string
          description: Original search query for display
        search_time:
          type: string
          format: date-time
          description: When the search was performed
        execution_time:
          type: number
          format: float
          description: Time taken to execute search in seconds

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error type identifier
        message:
          type: string
          description: Human-readable error message
        query_text:
          type: string
          description: Original search query that caused the error
