openapi: 3.0.0
info:
  title: Astro Web - Navigation Bar with Multi-Page Structure API
  description: Multi-page navigation with Home, Browse Database, and Visualizations pages
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /:
    get:
      summary: Home Page - Introduction to Database
      description: Displays the home page with introduction text about the astronomical database. Includes navigation bar.
      tags:
        - Web Pages
      responses:
        '200':
          description: Successfully rendered home page
          content:
            text/html:
              schema:
                type: string
                description: HTML page with navigation bar and introduction text
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /browse:
    get:
      summary: Browse Database Page - Sources Table
      description: Displays all Sources records in a sortable, filterable, paginated table
      tags:
        - Web Pages
      parameters:
        - name: page
          in: query
          description: Page number (1-based)
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          description: Rows per page
          schema:
            type: integer
            enum: [10, 25, 50, 100]
            default: 10
        - name: sort
          in: query
          description: Column to sort by
          schema:
            type: string
        - name: order
          in: query
          description: Sort order (asc or desc)
          schema:
            type: string
            enum: [asc, desc]
            default: asc
        - name: filter
          in: query
          description: Filter text to search across all columns
          schema:
            type: string
      responses:
        '200':
          description: Successfully rendered Browse Database page with Sources table
          content:
            text/html:
              schema:
                type: string
                description: HTML page with navigation bar and Sources table with controls
          headers:
            X-Sources-Count:
              description: Total number of Sources records
              schema:
                type: integer
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /plots:
    get:
      summary: Visualizations Page - Scatter Plot
      description: Displays interactive scatter plot of ra vs dec coordinates for all Sources
      tags:
        - Web Pages
      responses:
        '200':
          description: Successfully rendered Visualizations page with scatter plot
          content:
            text/html:
              schema:
                type: string
                description: HTML page with navigation bar and interactive scatter plot
          headers:
            X-Sources-Plotted:
              description: Number of Sources plotted (excludes null coordinates)
              schema:
                type: integer
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    NavigationItem:
      type: object
      description: A navigation bar item
      properties:
        label:
          type: string
          description: Display text
          example: "Home"
        route:
          type: string
          description: URL path
          example: "/"
        is_active:
          type: boolean
          description: Whether this is the current page
    Error:
      type: object
      properties:
        detail:
          type: string
          description: Error message
      example:
        detail: "Database temporarily unavailable"
tags:
  - name: Web Pages
    description: HTML page endpoints with navigation bar
  - name: Database
    description: Sources table data display and filtering


