openapi: 3.0.0
info:
  title: Spectra Display API
  version: 1.0.0
  description: API endpoints for spectra visualization functionality
servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /source/{source_name}/spectra:
    get:
      summary: Display spectra visualization for a source
      description: |
        Renders an interactive Bokeh plot displaying all spectra for a specified source,
        along with a metadata table showing observation details and clickable links to
        spectrum data files. Spectra are retrieved from the database via astrodbkit and
        returned already formatted - no additional format conversion needed.
      parameters:
        - name: source_name
          in: path
          required: true
          description: Source identifier (URL encoded)
          schema:
            type: string
          example: "HIP 65426"
      responses:
        '200':
          description: Spectra visualization page rendered successfully
          content:
            text/html:
              schema:
                type: string
          headers:
            X-Spectra-Count:
              schema:
                type: integer
              description: Number of spectra displayed
            X-Execution-Time:
              schema:
                type: number
              description: Page generation time in seconds
        '404':
          description: Source not found or no spectra available
          content:
            text/html:
              schema:
                type: string
              examples:
                source_not_found:
                  value: |
                    <div class="error-message">
                      <p>Source not found: HIP 65426</p>
                      <a href="/browse">Return to Browse</a>
                    </div>
                no_spectra_available:
                  value: |
                    <div class="no-spectra-message">
                      <p>No spectra available for display for this source.</p>
                    </div>
      tags:
        - Spectra
        - Sources

components:
  schemas:
    SpectrumMetadata:
      type: object
      description: Metadata for a single spectrum
      properties:
        observation_date:
          type: string
          description: Date of observation (ISO 8601 format or "-" if missing)
          example: "2020-03-15"
        regime:
          type: string
          description: Spectral regime (e.g., "optical", "near-infrared", "mid-infrared" or "-" if missing)
          example: "NIR"
        telescope:
          type: string
          description: Telescope used for observation (e.g., "JWST", "Keck" or "-" if missing)
          example: "JWST"
        instrument:
          type: string
          description: Instrument used for observation (e.g., "NIRSpec", "HIRES" or "-" if missing)
          example: "NIRSpec"
        access_url:
          type: string
          description: URL or path to spectrum data file
          example: "https://mast.stsci.edu/observation/.../spectrum.fits"
        legend_label:
          type: string
          description: Formatted label for plot legend (observation_date | regime | telescope/instrument)
          example: "2020-03-15 | NIR | JWST/NIRSpec"
    
    SpectraVisualization:
      type: object
      description: Complete spectra visualization data
      properties:
        source_name:
          type: string
          description: Source identifier
          example: "HIP 65426"
        plot_script:
          type: string
          description: Bokeh plot JavaScript code (embedded in HTML)
        plot_div:
          type: string
          description: Bokeh plot HTML container (embedded in HTML)
        spectra_metadata:
          type: array
          description: List of spectrum metadata dictionaries for table display
          items:
            $ref: '#/components/schemas/SpectrumMetadata'
        spectra_count:
          type: integer
          description: Number of spectra successfully loaded and displayed
          example: 5
        has_spectra:
          type: boolean
          description: Whether any spectra were successfully loaded and are displayed
          example: true

tags:
  - name: Spectra
    description: Spectra visualization endpoints
  - name: Sources
    description: Source-related endpoints

